version: '3'

services:
  core:
    build:
      context: core/
    ports:
      - "9999:9999"
    depends_on:
      - "db"
    networks:
      meteornet:
        ipv4_address: 172.69.1.1

  db:
    build:
      context: database/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      meteornet:
        ipv4_address: 172.69.1.2

networks:
  meteornet:
    ipam:
      driver: default
      config:
        - subnet: 172.69.0.0/16